apiVersion: v1
kind: Pod
metadata:
  name: app-pod-1
  labels:
    app: app
    ver: v10
spec:
  containers:
    - name: app-containers
      image: shekeriev/k8s-appa:v1
      ports:
        - containerPort: 80