apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels:
    app: app
    ver: v1
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30001
      protocol: TCP
  selector:
    app: app 