apiVersion: v1
kind: Pod
metadata:
  name: homework-2
  labels:
    app: hw
  namespace: homework
spec:
  containers:
  - name: oracle-2
    image: shekeriev/k8s-oracle
    ports:
    - containerPort: 5000
