apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oracle
  name: oracle-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oracle
  template:
    metadata:
      labels:
        app: oracle
    spec:
      containers:
      - image: shekeriev/k8s-oracle
        name: k8s-oracle
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-svc
spec:
  selector:
    app: oracle
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30500