apiVersion: v1
kind: Service
metadata:
  name: factsnp
spec:
  selector:
    app: fact # must be facts
  type: ClusterIP # must be NodePort
  ports:
  - port: 5000
    nodePort: 30001
    protocol: TCP
