apiVersion: v1
kind: Pod
metadata:
  name: hwpod
  labels:
    app: homework
spec:
  containers:
  - image: shekeriev/k8s-environ
    name: cont-homework
    volumeMounts:
    - mountPath: /config
      name: config-volume
    - mountPath: /secret
      name: secret-volume
    envFrom:
    - configMapRef:
        name: hwcm
      prefix: HW_ 
    env:
    - name: HW_PORT
      valueFrom:
        configMapKeyRef:
          name: hwcm
          key: port
  volumes:
  - name: config-volume
    configMap:
      name: hwcm
      items:
      - key: main.conf
        path: main.conf
  - name: secret-volume
    secret:
      secretName: hwsec
